ML EXP 2 

SUBMITTED BY : Gaurav Saxena

In [16]:
import numpy as np

1D Array Operations

In [35]:
#operations on 1D array 
a = np.array([1,2,3,4,5,6,7,8,9,10])

#print the dimensions of an array : It means the number of rows in the array
print('The dimensions of the array are :' , a.ndim)

#print the shape of the array : i.e. rows and colums
print('The shape of the array is :' , a.shape)

#print the data type of the array : what data type is stored in the array(int,string,float,etc)
print('The data type of the array is : ' , a.dtype)


The dimensions of the array are : 1
The shape of the array is : (10,)
The data type of the array is :  int64


2D ARRAY OPERATIONS 

In [20]:
b = np.array([[1,2,3,4,5,6],[9,10,11,12,13,14]],dtype=object)

print(b)
print(b.ndim)
print('The shape of the array is :' ,b.shape)

#reshaping the exisiting 1D array to 2D
bb = a.reshape((5,2))
print(bb)




[[1 2 3 4 5 6]
 [9 10 11 12 13 14]]
2
The shape of the array is : (2, 6)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Operations on Numpy Arrays


In [26]:
#element wise multiplication
print(a)
print(a*3)

#element wise square
print('=====================================')
print(a)
print(a**2)

#multiplying the list by a number does not result in multipliying each element instead it justs add number of times the element itself in the list
print('=====================================')
print([1,2,3,4]*3)

#if we do some changes in the original array,in this case 'a' then changes are also reflected in the reshaped array of that array
print('=====================================')
print(a)
a[0] = 20
print(bb)


[20  2  3  4  5  6  7  8  9 10]
[60  6  9 12 15 18 21 24 27 30]
[20  2  3  4  5  6  7  8  9 10]
[400   4   9  16  25  36  49  64  81 100]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[20  2  3  4  5  6  7  8  9 10]
[[20  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Creating a numpy array copy

In [29]:
c = a.reshape(5,2).copy()
print(c)
c[0][1] = 30
c[1][0] = 45
print("====")
print(c)
print('=====')
print(a)

[[20  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
====
[[20 30]
 [45  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
=====
[20  2  3  4  5  6  7  8  9 10]


Indexing in Numpy arrays

In [37]:
print(a[0])

##printing multiple elements at specific index
print(a[np.array([1,3])])

#printing elements according to a specific condition
print('Even elements in the array are' , a[a%2 == 0])

#other conditions that can be
a[a>4] = 10
print(a)
#gives how many elements greater than 4 and that are convertred to 10

a[a==10] = 12
print(a)

1
[2 4]
Even elements in the array are [ 2  4 10 10 10 10 10 10]
[ 1  2  3  4 10 10 10 10 10 10]
[ 1  2  3  4 12 12 12 12 12 12]


Clipping

In [40]:
f = np.array([1,2,4,5,2,8])
d = f.copy()
print(d)

print(d.clip(3,5)) 
#elements  less than 3 are made 3 and those greater than 5 are made 5

[1 2 4 5 2 8]
[3 3 4 5 3 5]
